import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('en'));
  }

  static const _localizedValues = <String, Map<String, String>>{
    'en': {
      'appName': 'Sharaby Center',
      'appSubtitle': 'Pediatric Healthcare & Child Development',
      // Onboarding
      'onboarding1Title': 'Welcome to Sharaby Center',
      'onboarding1Desc':
          'Pediatric healthcare management made simple.',
      'onboarding2Title': 'Manage Pediatric Patients',
      'onboarding2Desc':
          'Keep children\'s medical records organized and accessible.',
      'onboarding3Title': 'Better Pediatric Care',
      'onboarding3Desc':
          'Access patient information, prescriptions and medical history from one place.',
      'btnNext': 'Next',
      'btnBack': 'Back',
      'btnGetStarted': 'Get Started',
      'btnSkip': 'Skip',
      // Auth & Login
      'loginTitle': 'Welcome Back',
      'loginSubtitle': 'Sign in to Sharaby Pediatric Center',
      'emailLabel': 'Email Address',
      'passwordLabel': 'Password',
      'confirmPasswordLabel': 'Confirm Password',
      'rememberMe': 'Remember Me',
      'forgotPassword': 'Forgot Password?',
      'signIn': 'Sign In',
      'signUp': 'Sign Up',
      'noAccount': "Don't have an account?",
      'haveAccount': 'Already have an account?',
      'staffRegistration': 'Staff Registration',
      'createStaffAccount': 'Create Staff Account',
      'registerStaffSubtitle': 'Register pediatric clinic staff for Sharaby Center',
      'roleInClinic': 'Role in Clinic',
      'roleDoctor': 'Pediatrician / Children\'s Doctor',
      'roleReceptionist': 'Receptionist',
      'roleNurse': 'Clinic Staff / Nurse',
      'createAccount': 'CREATE ACCOUNT',
      'fillRequiredFields': 'Please fill in all required fields',
      'passwordsDoNotMatch': 'Passwords do not match',
      'loginFailed': 'Login failed',
      'signupFailed': 'Signup failed',
      'resetPasswordTitle': 'Reset Password',
      'resetPasswordDesc': 'Enter your email to receive password reset instructions.',
      'sendResetLink': 'Send Reset Link',
      // Navigation
      'navDashboard': 'Dashboard',
      'navPatients': 'Pediatric Patients',
      'navAppointments': 'Appointments',
      'navPrescriptions': 'Prescriptions',
      'navBilling': 'Billing',
      'navReports': 'Reports',
      'navDocuments': 'Documents',
      'navNotifications': 'Notifications',
      'navProfile': 'Profile',
      'navSettings': 'Settings',
      'navAbout': 'About',
      'navLogout': 'Logout',
      // Dashboard
      'greetingDay': 'Good Day,',
      'doctorRole': 'Consultant Pediatrician & Neonatologist',
      'searchPlaceholder': 'Search children, parent names, IDs...',
      'medicalBannerTitle': 'Pediatric Healthcare Excellence',
      'medicalBannerSubtitle':
          'Dedicated healthcare and growth tracking for infants, children, and adolescents.',
      'statTotalPatients': 'Pediatric Patients',
      'statAppointments': "Today's Pediatric Visits",
      'statPrescriptions': 'Pediatric Prescriptions',
      'statBilling': 'Total Revenue',
      'quickActions': 'Quick Actions',
      'actionAddPatient': 'Register Child',
      'actionNewPrescription': 'New Rx',
      'actionCreateInvoice': 'New Invoice',
      'actionViewReports': 'Reports',
      'todaysActivity': "Today's Pediatric Visits",
      'recentPatients': 'Recent Pediatric Patients',
      'recentPrescriptions': 'Pediatric Prescriptions',
      'recentBilling': 'Recent Invoices',
      'viewAll': 'View All',
      'clinicOverview': 'Pediatric Overview',
      // Financial Security
      'enterSecurityCode': 'Security Verification',
      'securityCodePrompt': 'Enter your 4-digit security PIN (Default: 1234) to reveal financial details:',
      'incorrectSecurityCode': 'Incorrect Security Code',
      'verify': 'Verify',
      // Profile
      'editProfile': 'Edit Profile',
      'fullName': 'Full Name',
      'phone': 'Phone Number',
      'email': 'Email Address',
      'address': 'Clinic Address',
      'saveChanges': 'Save Changes',
      'cancel': 'Cancel',
      'profileUpdated': 'Profile updated successfully!',
      // Settings
      'settingsTitle': 'Settings',
      'appearance': 'Appearance & Theme',
      'darkMode': 'Dark Mode',
      'language': 'Language / اللغة',
      'notifications': 'Push Notifications',
      'about': 'About Sharaby Pediatric Center',
      'privacy': 'Privacy Policy',
      'version': 'App Version 1.0.0',
      'english': 'English',
      'arabic': 'العربية (Arabic)',
      // Notifications
      'notificationsTitle': 'Notifications',
      'all': 'All',
      'unread': 'Unread',
      'markAllRead': 'Mark all read',
      // Documents
      'documentsTitle': 'Pediatric Records & Documents',
      'exportSubtitle': 'Export pediatric database into CSV format.',
      'downloadCsv': 'Download CSV',
      'csvSuccess': 'CSV generated and saved successfully!',
      'shareFile': 'Share File',
      'allFiles': 'All Files',
      'noDocumentsFound': 'No Documents Found',
      'noFilesMatch': 'No files match your search criteria.',
      'noPatientsFound': 'No Pediatric Patients Found',
      // Patients Feature & Pediatric Fields
      'patientManagement': 'Pediatric Patients',
      'addNewPatient': 'Register Child',
      'editPatient': 'Edit Child Record',
      'childName': "Child's Name",
      'fatherName': "Father's Name",
      'motherName': "Mother's Name",
      'guardianPhone': 'Parent/Guardian Phone',
      'weight': 'Weight',
      'height': 'Height',
      'bmi': 'BMI',
      'growthStatus': 'Growth Status',
      'vaccinationStatus': 'Vaccination Status',
      'growth': 'Growth & Vitals',
      'parentGuardian': 'Parent / Guardian',
      'age': 'Age',
      'gender': 'Gender',
      'male': 'Male',
      'female': 'Female',
      'medicalHistory': 'Medical History',
      'diagnosis': 'Diagnosis',
      'patientDetails': 'Pediatric Patient Details',
      'patientAdded': 'Child registered successfully',
      'patientUpdated': 'Patient updated successfully',
      'deletePatient': 'Delete Child Record',
      'confirmDeletePatient': 'Are you sure you want to delete this child\'s medical record?',
      'delete': 'Delete',
      // Billing Feature
      'billingTitle': 'Billing & Invoices',
      'collectedRevenue': 'Collected Revenue',
      'pendingBalances': 'Pending Balances',
      'createInvoice': 'Create Invoice',
      'invoiceNumber': 'Invoice #',
      'amount': 'Amount',
      'status': 'Status',
      'paid': 'Paid',
      'unpaid': 'Unpaid',
      'pending': 'Pending',
      'overdue': 'Overdue',
      'issueDate': 'Issue Date',
      'dueDate': 'Due Date',
      'noInvoicesFound': 'No Invoices Found',
      // Reports & Analytics
      'reportsTitle': 'Reports & Analytics',
      'performanceSummary': 'Performance Summary',
      'revenueGrowth': 'Revenue Growth Trend',
      'monthlyRevenue': 'Monthly Revenue (EGP)',
      'totalRevenue': 'Total Revenue',
      'patientVisits': 'Pediatric Visits',
      'appointmentsCompleted': 'Appointments Completed',
      'outstandingCollections': 'Outstanding Collections',
      'exportPdf': 'Export PDF',
      'exportExcel': 'Export Excel',
      'thisWeek': 'This Week',
      'thisMonth': 'This Month',
      'thisYear': 'This Year',
      // Prescriptions
      'prescriptionsTitle': 'Pediatric Prescriptions',
      'newPrescription': 'New Prescription',
      'medication': 'Medication',
      'dosage': 'Pediatric Dosage',
      'frequency': 'Frequency',
      'duration': 'Duration',
      'notes': 'Notes / Instructions',
      'rxNumber': 'Rx #',
      'issueRx': 'Issue Prescription',
      // Dialogs & System
      'confirmSignOutTitle': 'Sign Out',
      'confirmSignOutDesc': 'Are you sure you want to sign out of Sharaby Center?',
      'confirm': 'Confirm',
      'close': 'Close',
    },
    'ar': {
      'appName': 'مركز شرابي للأطفال',
      'appSubtitle': 'رعاية الأطفال وتتبع النمو والمتابعة الدورية',
      // Onboarding
      'onboarding1Title': 'مرحباً بك في مركز شرابي',
      'onboarding1Desc':
          'إدارة عيادة طب الأطفال ورعايتهم ببساطة واحترافية.',
      'onboarding2Title': 'إدارة مرضى الأطفال',
      'onboarding2Desc':
          'تنظيم السجلات الطبية للأطفال وجداول النمو والتطعيمات بسهولة.',
      'onboarding3Title': 'رعاية أفضل للأطفال',
      'onboarding3Desc':
          'الوصول لبيانات الأطفال والروشتات وتاريخهم الطبي من مكان واحد.',
      'btnNext': 'التالي',
      'btnBack': 'السابق',
      'btnGetStarted': 'ابدأ الآن',
      'btnSkip': 'تخطي',
      // Auth & Login
      'loginTitle': 'مرحباً بعودتك',
      'loginSubtitle': 'تسجيل الدخول لمركز شرابي لطب الأطفال',
      'emailLabel': 'البريد الإلكتروني',
      'passwordLabel': 'كلمة المرور',
      'confirmPasswordLabel': 'تأكيد كلمة المرور',
      'rememberMe': 'تذكرني',
      'forgotPassword': 'نسيت كلمة المرور؟',
      'signIn': 'تسجيل الدخول',
      'signUp': 'إنشاء حساب',
      'noAccount': 'ليس لديك حساب؟',
      'haveAccount': 'لديك حساب بالفعل؟',
      'staffRegistration': 'تسجيل الطاقم الطبي',
      'createStaffAccount': 'إنشاء حساب موظف',
      'registerStaffSubtitle': 'تسجيل أعضاء الطاقم الطبي في مركز شرابي للأطفال',
      'roleInClinic': 'الدور في العيادة',
      'roleDoctor': 'طبيب أطفال / أخصائي أطفال',
      'roleReceptionist': 'موظف استقبال',
      'roleNurse': 'طاقم تمريض / عيادة',
      'createAccount': 'إنشاء الحساب',
      'fillRequiredFields': 'يرجى ملء جميع الحقول المطلوبة',
      'passwordsDoNotMatch': 'كلمتا المرور غير متطابقتين',
      'loginFailed': 'فشل تسجيل الدخول',
      'signupFailed': 'فشل إنشاء الحساب',
      'resetPasswordTitle': 'استعادة كلمة المرور',
      'resetPasswordDesc': 'أدخل بريدك الإلكتروني لاستلام تعليمات إعادة تعيين كلمة المرور.',
      'sendResetLink': 'إرسال رابط التعيين',
      // Navigation
      'navDashboard': 'لوحة التحكم',
      'navPatients': 'المرضى الأطفال',
      'navAppointments': 'المواعيد',
      'navPrescriptions': 'الروشتات',
      'navBilling': 'الفواتير',
      'navReports': 'التقارير',
      'navDocuments': 'المستندات',
      'navNotifications': 'الإشعارات',
      'navProfile': 'الملف الشخصي',
      'navSettings': 'الإعدادات',
      'navAbout': 'عن التطبيق',
      'navLogout': 'تسجيل الخروج',
      // Dashboard
      'greetingDay': 'يوم سعيد،',
      'doctorRole': 'استشاري طب الأطفال وحديثي الولادة',
      'searchPlaceholder': 'البحث عن الأطفال، أولياء الأمور، الرقم...',
      'medicalBannerTitle': 'تميز رعاية الأطفال بمركز شرابي',
      'medicalBannerSubtitle':
          'رعاية متخصصة ومتابعة دقيقة للنمو والتطعيمات لحديثي الولادة والأطفال واليافعين.',
      'statTotalPatients': 'المرضى الأطفال',
      'statAppointments': 'زيارات الأطفال اليوم',
      'statPrescriptions': 'روشتات الأطفال',
      'statBilling': 'إجمالي الإيرادات',
      'quickActions': 'إجراءات سريعة',
      'actionAddPatient': 'تسجيل طفل',
      'actionNewPrescription': 'روشتة جديدة',
      'actionCreateInvoice': 'فاتورة جديدة',
      'actionViewReports': 'التقارير',
      'todaysActivity': 'زيارات الأطفال اليوم',
      'recentPatients': 'أحدث المرضى الأطفال',
      'recentPrescriptions': 'أحدث روشتات الأطفال',
      'recentBilling': 'أحدث الفواتير',
      'viewAll': 'عرض الكل',
      'clinicOverview': 'نظرة عامة على العيادة',
      // Financial Security
      'enterSecurityCode': 'التحقق الأمني',
      'securityCodePrompt': 'أدخل رمز الأمان المكون من 4 أرقام (الافتراضي: 1234) لعرض البيانات المالية:',
      'incorrectSecurityCode': 'رمز الأمان غير صحيح',
      'verify': 'تأكيد',
      // Profile
      'editProfile': 'تعديل الملف الشخصي',
      'fullName': 'الاسم بالكامل',
      'phone': 'رقم الهاتف',
      'email': 'البريد الإلكتروني',
      'address': 'عنوان العيادة',
      'saveChanges': 'حفظ التغييرات',
      'cancel': 'إلغاء',
      'profileUpdated': 'تم تحديث الملف الشخصي بنجاح!',
      // Settings
      'settingsTitle': 'الإعدادات',
      'appearance': 'المظهر والمظهر الداكن',
      'darkMode': 'الوضع الداكن',
      'language': 'اللغة / Language',
      'notifications': 'التنبيهات والإشعارات',
      'about': 'عن مركز شرابي للأطفال',
      'privacy': 'سياسة الخصوصية',
      'version': 'إصدار التطبيق 1.0.0',
      'english': 'English',
      'arabic': 'العربية (Arabic)',
      // Notifications
      'notificationsTitle': 'الإشعارات',
      'all': 'الكل',
      'unread': 'غير مقروء',
      'markAllRead': 'تحديد الكل كمقروء',
      // Documents
      'documentsTitle': 'مستندات ورعاية الأطفال',
      'exportSubtitle': 'تصدير قاعدة بيانات الأطفال بصيغة CSV.',
      'downloadCsv': 'تحميل ملف CSV',
      'csvSuccess': 'تم إنشاء وحفظ ملف CSV بنجاح!',
      'shareFile': 'مشاركة الملف',
      'allFiles': 'جميع الملفات',
      'noDocumentsFound': 'لم يتم العثور على مستندات',
      'noFilesMatch': 'لا توجد ملفات تطابق معايير البحث.',
      'noPatientsFound': 'لم يتم العثور على مرضى أطفال',
      // Patients Feature & Pediatric Fields
      'patientManagement': 'المرضى الأطفال',
      'addNewPatient': 'تسجيل طفل',
      'editPatient': 'تعديل بيانات الطفل',
      'childName': 'اسم الطفل',
      'fatherName': 'اسم الأب',
      'motherName': 'اسم الأم',
      'guardianPhone': 'هاتف ولي الأمر',
      'weight': 'الوزن',
      'height': 'الطول',
      'bmi': 'مؤشر كتلة الجسم',
      'growthStatus': 'معدل النمو',
      'vaccinationStatus': 'حالة التطعيمات',
      'growth': 'النمو والقياسات',
      'parentGuardian': 'ولي الأمر',
      'age': 'العمر',
      'gender': 'الجنس',
      'male': 'ذكر',
      'female': 'أنثى',
      'medicalHistory': 'التاريخ الطبي',
      'diagnosis': 'التشخيص',
      'patientDetails': 'تفاصيل المريض الطفل',
      'patientAdded': 'تم تسجيل الطفل بنجاح',
      'patientUpdated': 'تم تحديث بيانات الطفل بنجاح',
      'deletePatient': 'حذف سجل الطفل',
      'confirmDeletePatient': 'هل أنت تأكد من رغبتك في حذف سجل هذا الطفل؟',
      'delete': 'حذف',
      // Billing Feature
      'billingTitle': 'الفواتير والحسابات',
      'collectedRevenue': 'الإيرادات المحصلة',
      'pendingBalances': 'المبالغ المتبقية',
      'createInvoice': 'إنشاء فاتورة',
      'invoiceNumber': 'رقم الفاتورة #',
      'amount': 'المبلغ',
      'status': 'الحالة',
      'paid': 'مدفوع',
      'unpaid': 'غير مدفوع',
      'pending': 'قيد الانتظار',
      'overdue': 'متأخر',
      'issueDate': 'تاريخ الإصدار',
      'dueDate': 'تاريخ الاستحقاق',
      'noInvoicesFound': 'لم يتم العثور على فواتير',
      // Reports & Analytics
      'reportsTitle': 'التقارير والتحليلات',
      'performanceSummary': 'ملخص الأداء',
      'revenueGrowth': 'اتجاه نمو الإيرادات',
      'monthlyRevenue': 'الإيرادات الشهرية (جنيه مصري)',
      'totalRevenue': 'إجمالي الإيرادات',
      'patientVisits': 'زيارات الأطفال',
      'appointmentsCompleted': 'المواعيد المكتملة',
      'outstandingCollections': 'المستحقات المتبقية',
      'exportPdf': 'تصدير PDF',
      'exportExcel': 'تصدير Excel',
      'thisWeek': 'هذا الأسبوع',
      'thisMonth': 'هذا الشهر',
      'thisYear': 'هذه السنة',
      // Prescriptions
      'prescriptionsTitle': 'روشتات الأطفال الطبية',
      'newPrescription': 'روشتة جديدة',
      'medication': 'الدواء',
      'dosage': 'جرعة الأطفال',
      'frequency': 'التكرار',
      'duration': 'المدة',
      'notes': 'ملاحظات / تعليمات',
      'rxNumber': 'روشتة #',
      'issueRx': 'إصدار الروشتة',
      // Dialogs & System
      'confirmSignOutTitle': 'تسجيل الخروج',
      'confirmSignOutDesc': 'هل أنت تأكد من رغبتك في تسجيل الخروج من مركز شرابي للأطفال؟',
      'confirm': 'تأكيد',
      'close': 'إغلاق',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }
}

class AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
