import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('en'));
  }

  static const _localizedValues = <String, Map<String, String>>{
    'en': {
      'appName': 'Sharaby Center',
      'appSubtitle': 'Healthcare Management Solution',
      // Onboarding
      'onboarding1Title': 'Welcome to Sharaby Center',
      'onboarding1Desc':
          'Modern Hospital Management System tailored for doctors, receptionists and clinic staff.',
      'onboarding2Title': 'Manage Patients Easily',
      'onboarding2Desc':
          'Seamlessly track appointments, prescriptions, patient histories, billing and diagnostic reports.',
      'onboarding3Title': 'Real-Time Clinic Access',
      'onboarding3Desc':
          'Access clinic data securely anytime with real-time cloud synchronization on mobile.',
      'btnNext': 'Next',
      'btnBack': 'Back',
      'btnGetStarted': 'Get Started',
      'btnSkip': 'Skip',
      // Auth & Login
      'loginTitle': 'Welcome Back',
      'loginSubtitle': 'Sign in to access Sharaby Center',
      'emailLabel': 'Email Address',
      'passwordLabel': 'Password',
      'confirmPasswordLabel': 'Confirm Password',
      'rememberMe': 'Remember Me',
      'forgotPassword': 'Forgot Password?',
      'signIn': 'Sign In',
      'signUp': 'Sign Up',
      'noAccount': "Don't have an account?",
      'haveAccount': 'Already have an account?',
      'staffRegistration': 'Staff Registration',
      'createStaffAccount': 'Create Staff Account',
      'registerStaffSubtitle': 'Register medical staff for Sharaby Center',
      'roleInClinic': 'Role in Clinic',
      'roleDoctor': 'Doctor / Physician',
      'roleReceptionist': 'Receptionist',
      'roleNurse': 'Clinic Staff / Nurse',
      'createAccount': 'CREATE ACCOUNT',
      'fillRequiredFields': 'Please fill in all required fields',
      'passwordsDoNotMatch': 'Passwords do not match',
      'loginFailed': 'Login failed',
      'signupFailed': 'Signup failed',
      'resetPasswordTitle': 'Reset Password',
      'resetPasswordDesc': 'Enter your email to receive password reset instructions.',
      'sendResetLink': 'Send Reset Link',
      // Navigation
      'navDashboard': 'Dashboard',
      'navPatients': 'Patients',
      'navAppointments': 'Appointments',
      'navPrescriptions': 'Prescriptions',
      'navBilling': 'Billing',
      'navReports': 'Reports',
      'navDocuments': 'Documents',
      'navNotifications': 'Notifications',
      'navProfile': 'Profile',
      'navSettings': 'Settings',
      'navAbout': 'About',
      'navLogout': 'Logout',
      // Dashboard
      'greetingDay': 'Good Day,',
      'doctorRole': 'Clinic Director / Doctor',
      'searchPlaceholder': 'Search patients, prescriptions, records...',
      'medicalBannerTitle': 'Sharaby Medical Excellence',
      'medicalBannerSubtitle':
          'Providing top quality healthcare and patient management services with modern precision.',
      'statTotalPatients': 'Total Patients',
      'statAppointments': "Today's Visits",
      'statPrescriptions': 'Prescriptions',
      'statBilling': 'Total Revenue',
      'quickActions': 'Quick Actions',
      'actionAddPatient': 'Add Patient',
      'actionNewPrescription': 'New Rx',
      'actionCreateInvoice': 'New Invoice',
      'actionViewReports': 'Reports',
      'todaysActivity': "Today's Activity",
      'recentPatients': 'Recent Patients',
      'recentPrescriptions': 'Recent Prescriptions',
      'recentBilling': 'Recent Invoices',
      'viewAll': 'View All',
      'clinicOverview': 'Clinic Overview',
      // Financial Security
      'enterSecurityCode': 'Security Verification',
      'securityCodePrompt': 'Enter your 4-digit security PIN (Default: 1234) to reveal financial details:',
      'incorrectSecurityCode': 'Incorrect Security Code',
      'verify': 'Verify',
      // Profile
      'editProfile': 'Edit Profile',
      'fullName': 'Full Name',
      'phone': 'Phone Number',
      'email': 'Email Address',
      'address': 'Clinic Address',
      'saveChanges': 'Save Changes',
      'cancel': 'Cancel',
      'profileUpdated': 'Profile updated successfully!',
      // Settings
      'settingsTitle': 'Settings',
      'appearance': 'Appearance & Theme',
      'darkMode': 'Dark Mode',
      'language': 'Language / اللغة',
      'notifications': 'Push Notifications',
      'about': 'About Sharaby Center',
      'privacy': 'Privacy Policy',
      'version': 'App Version 1.0.0',
      'english': 'English',
      'arabic': 'العربية (Arabic)',
      // Notifications
      'notificationsTitle': 'Notifications',
      'all': 'All',
      'unread': 'Unread',
      'markAllRead': 'Mark all read',
      // Documents
      'documentsTitle': 'Clinic Documents',
      'exportSubtitle': 'Export clinic patient database into CSV format.',
      'downloadCsv': 'Download CSV',
      'csvSuccess': 'CSV generated and saved successfully!',
      'shareFile': 'Share File',
      'allFiles': 'All Files',
      'noDocumentsFound': 'No Documents Found',
      'noFilesMatch': 'No files match your search criteria.',
      'noPatientsFound': 'No Patients Found',
      // Patients Feature
      'patientManagement': 'Patient Management',
      'addNewPatient': 'Add New Patient',
      'editPatient': 'Edit Patient',
      'age': 'Age',
      'gender': 'Gender',
      'male': 'Male',
      'female': 'Female',
      'medicalHistory': 'Medical History',
      'diagnosis': 'Diagnosis',
      'patientDetails': 'Patient Details',
      'patientAdded': 'Patient added successfully',
      'patientUpdated': 'Patient updated successfully',
      'deletePatient': 'Delete Patient',
      'confirmDeletePatient': 'Are you sure you want to delete this patient record?',
      'delete': 'Delete',
      // Billing Feature
      'billingTitle': 'Billing & Invoices',
      'collectedRevenue': 'Collected Revenue',
      'pendingBalances': 'Pending Balances',
      'createInvoice': 'Create Invoice',
      'invoiceNumber': 'Invoice #',
      'amount': 'Amount',
      'status': 'Status',
      'paid': 'Paid',
      'unpaid': 'Unpaid',
      'pending': 'Pending',
      'overdue': 'Overdue',
      'issueDate': 'Issue Date',
      'dueDate': 'Due Date',
      'noInvoicesFound': 'No Invoices Found',
      // Reports & Analytics
      'reportsTitle': 'Reports & Analytics',
      'performanceSummary': 'Performance Summary',
      'revenueGrowth': 'Revenue Growth Trend',
      'monthlyRevenue': 'Monthly Revenue (EGP)',
      'totalRevenue': 'Total Revenue',
      'patientVisits': 'Patient Visits',
      'appointmentsCompleted': 'Appointments Completed',
      'outstandingCollections': 'Outstanding Collections',
      'exportPdf': 'Export PDF',
      'exportExcel': 'Export Excel',
      'thisWeek': 'This Week',
      'thisMonth': 'This Month',
      'thisYear': 'This Year',
      // Prescriptions
      'prescriptionsTitle': 'Prescriptions',
      'newPrescription': 'New Prescription',
      'medication': 'Medication',
      'dosage': 'Dosage',
      'frequency': 'Frequency',
      'duration': 'Duration',
      'notes': 'Notes / Instructions',
      'rxNumber': 'Rx #',
      'issueRx': 'Issue Prescription',
      // Dialogs & System
      'confirmSignOutTitle': 'Sign Out',
      'confirmSignOutDesc': 'Are you sure you want to sign out of Sharaby Center?',
      'confirm': 'Confirm',
      'close': 'Close',
    },
    'ar': {
      'appName': 'مركز شرابي الطبى',
      'appSubtitle': 'حل إدارة الرعاية الصحية المتكامل',
      // Onboarding
      'onboarding1Title': 'مرحباً بك في مركز شرابي',
      'onboarding1Desc':
          'نظام متطور لإدارة المستشفيات والعيادات مخصص للأطباء وموظفي الاستقبال والطاقم الطبي.',
      'onboarding2Title': 'إدارة المرضى بسهولة',
      'onboarding2Desc':
          'إدارة المواعيد والروشتات والسجل الطبي والفواتير والتقارير الطبية بسلاسة فائقة.',
      'onboarding3Title': 'تواصل فورى من أي مكان',
      'onboarding3Desc':
          'الوصول إلى بيانات العيادة بأمان في أي وقت مع المزامنة السحابية الفورية على الجوال.',
      'btnNext': 'التالي',
      'btnBack': 'السابق',
      'btnGetStarted': 'ابدأ الآن',
      'btnSkip': 'تخطي',
      // Auth & Login
      'loginTitle': 'مرحباً بعودتك',
      'loginSubtitle': 'تسجيل الدخول للوصول إلى مركز شرابي',
      'emailLabel': 'البريد الإلكتروني',
      'passwordLabel': 'كلمة المرور',
      'confirmPasswordLabel': 'تأكيد كلمة المرور',
      'rememberMe': 'تذكرني',
      'forgotPassword': 'نسيت كلمة المرور؟',
      'signIn': 'تسجيل الدخول',
      'signUp': 'إنشاء حساب',
      'noAccount': 'ليس لديك حساب؟',
      'haveAccount': 'لديك حساب بالفعل؟',
      'staffRegistration': 'تسجيل الطاقم الطبي',
      'createStaffAccount': 'إنشاء حساب موظف',
      'registerStaffSubtitle': 'تسجيل أعضاء الطاقم الطبي في مركز شرابي',
      'roleInClinic': 'الدور في العيادة',
      'roleDoctor': 'طبيب / ممارس عام',
      'roleReceptionist': 'موظف استقبال',
      'roleNurse': 'طاقم تمريض / عيادة',
      'createAccount': 'إنشاء الحساب',
      'fillRequiredFields': 'يرجى ملء جميع الحقول المطلوبة',
      'passwordsDoNotMatch': 'كلمتا المرور غير متطابقتين',
      'loginFailed': 'فشل تسجيل الدخول',
      'signupFailed': 'فشل إنشاء الحساب',
      'resetPasswordTitle': 'استعادة كلمة المرور',
      'resetPasswordDesc': 'أدخل بريدك الإلكتروني لاستلام تعليمات إعادة تعيين كلمة المرور.',
      'sendResetLink': 'إرسال رابط التعيين',
      // Navigation
      'navDashboard': 'لوحة التحكم',
      'navPatients': 'المرضى',
      'navAppointments': 'المواعيد',
      'navPrescriptions': 'الروشتات',
      'navBilling': 'الفواتير',
      'navReports': 'التقارير',
      'navDocuments': 'المستندات',
      'navNotifications': 'الإشعارات',
      'navProfile': 'الملف الشخصي',
      'navSettings': 'الإعدادات',
      'navAbout': 'عن التطبيق',
      'navLogout': 'تسجيل الخروج',
      // Dashboard
      'greetingDay': 'يوم سعيد،',
      'doctorRole': 'مدير العيادة / طبيب',
      'searchPlaceholder': 'البحث عن مرضى، روشتات، سجلات...',
      'medicalBannerTitle': 'تميز مركز شرابي الطبي',
      'medicalBannerSubtitle':
          'تقديم أفضل خدمات الرعاية الصحية وإدارة المرضى بأعلى معايير الدقة والاحترافية.',
      'statTotalPatients': 'إجمالي المرضى',
      'statAppointments': 'زيارات اليوم',
      'statPrescriptions': 'الروشتات النشطة',
      'statBilling': 'إجمالي الإيرادات',
      'quickActions': 'إجراءات سريعة',
      'actionAddPatient': 'إضافة مريض',
      'actionNewPrescription': 'روشتة جديدة',
      'actionCreateInvoice': 'فاتورة جديدة',
      'actionViewReports': 'التقارير',
      'todaysActivity': 'نشاط اليوم',
      'recentPatients': 'أحدث المرضى',
      'recentPrescriptions': 'أحدث الروشتات',
      'recentBilling': 'أحدث الفواتير',
      'viewAll': 'عرض الكل',
      'clinicOverview': 'نظرة عامة على العيادة',
      // Financial Security
      'enterSecurityCode': 'التحقق الأمني',
      'securityCodePrompt': 'أدخل رمز الأمان المكون من 4 أرقام (الافتراضي: 1234) لعرض البيانات المالية:',
      'incorrectSecurityCode': 'رمز الأمان غير صحيح',
      'verify': 'تأكيد',
      // Profile
      'editProfile': 'تعديل الملف الشخصي',
      'fullName': 'الاسم بالكامل',
      'phone': 'رقم الهاتف',
      'email': 'البريد الإلكتروني',
      'address': 'عنوان العيادة',
      'saveChanges': 'حفظ التغييرات',
      'cancel': 'إلغاء',
      'profileUpdated': 'تم تحديث الملف الشخصي بنجاح!',
      // Settings
      'settingsTitle': 'الإعدادات',
      'appearance': 'المظهر والمظهر الداكن',
      'darkMode': 'الوضع الداكن',
      'language': 'اللغة / Language',
      'notifications': 'التنبيهات والإشعارات',
      'about': 'عن مركز شرابي',
      'privacy': 'سياسة الخصوصية',
      'version': 'إصدار التطبيق 1.0.0',
      'english': 'English',
      'arabic': 'العربية (Arabic)',
      // Notifications
      'notificationsTitle': 'الإشعارات',
      'all': 'الكل',
      'unread': 'غير مقروء',
      'markAllRead': 'تحديد الكل كمقروء',
      // Documents
      'documentsTitle': 'مستندات العيادة',
      'exportSubtitle': 'تصدير قاعدة بيانات المرضى بصيغة CSV.',
      'downloadCsv': 'تحميل ملف CSV',
      'csvSuccess': 'تم إنشاء وحفظ ملف CSV بنجاح!',
      'shareFile': 'مشاركة الملف',
      'allFiles': 'جميع الملفات',
      'noDocumentsFound': 'لم يتم العثور على مستندات',
      'noFilesMatch': 'لا توجد ملفات تطابق معايير البحث.',
      'noPatientsFound': 'لم يتم العثور على مرضى',
      // Patients Feature
      'patientManagement': 'إدارة المرضى',
      'addNewPatient': 'إضافة مريض جديد',
      'editPatient': 'تعديل بيانات المريض',
      'age': 'العمر',
      'gender': 'الجنس',
      'male': 'ذكر',
      'female': 'أنثى',
      'medicalHistory': 'التاريخ الطبي',
      'diagnosis': 'التشخيص',
      'patientDetails': 'تفاصيل المريض',
      'patientAdded': 'تمت إضافة المريض بنجاح',
      'patientUpdated': 'تم تحديث بيانات المريض بنجاح',
      'deletePatient': 'حذف المريض',
      'confirmDeletePatient': 'هل أنت تأكد من رغبتك في حذف سجل هذا المريض؟',
      'delete': 'حذف',
      // Billing Feature
      'billingTitle': 'الفواتير والحسابات',
      'collectedRevenue': 'الإيرادات المحصلة',
      'pendingBalances': 'المبالغ المتبقية',
      'createInvoice': 'إنشاء فاتورة',
      'invoiceNumber': 'رقم الفاتورة #',
      'amount': 'المبلغ',
      'status': 'الحالة',
      'paid': 'مدفوع',
      'unpaid': 'غير مدفوع',
      'pending': 'قيد الانتظار',
      'overdue': 'متأخر',
      'issueDate': 'تاريخ الإصدار',
      'dueDate': 'تاريخ الاستحقاق',
      'noInvoicesFound': 'لم يتم العثور على فواتير',
      // Reports & Analytics
      'reportsTitle': 'التقارير والتحليلات',
      'performanceSummary': 'ملخص الأداء',
      'revenueGrowth': 'اتجاه نمو الإيرادات',
      'monthlyRevenue': 'الإيرادات الشهرية (جنيه مصري)',
      'totalRevenue': 'إجمالي الإيرادات',
      'patientVisits': 'زيارات المرضى',
      'appointmentsCompleted': 'المواعيد المكتملة',
      'outstandingCollections': 'المستحقات المتبقية',
      'exportPdf': 'تصدير PDF',
      'exportExcel': 'تصدير Excel',
      'thisWeek': 'هذا الأسبوع',
      'thisMonth': 'هذا الشهر',
      'thisYear': 'هذه السنة',
      // Prescriptions
      'prescriptionsTitle': 'الروشتات الطبية',
      'newPrescription': 'روشتة جديدة',
      'medication': 'الدواء',
      'dosage': 'الجرعة',
      'frequency': 'التكرار',
      'duration': 'المدة',
      'notes': 'ملاحظات / تعليمات',
      'rxNumber': 'روشتة #',
      'issueRx': 'إصدار الروشتة',
      // Dialogs & System
      'confirmSignOutTitle': 'تسجيل الخروج',
      'confirmSignOutDesc': 'هل أنت تأكد من رغبتك في تسجيل الخروج من مركز شرابي؟',
      'confirm': 'تأكيد',
      'close': 'إغلاق',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }
}

class AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
