// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdniS7y5aIY0Ds_zqSnVfuTet3pS6fL3c',
    appId: '1:33236853941:web:6b400f5252b17f158b4afc',
    messagingSenderId: '33236853941',
    projectId: 'sharaby-center',
    authDomain: 'sharaby-center.firebaseapp.com',
    storageBucket: 'sharaby-center.firebasestorage.app',
    measurementId: 'G-4Z0LY1M7FM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpM8sWJqTxbRiVbhSY1R-OAlvnEr_V7P8',
    appId: '1:33236853941:android:5e5deab2a57560858b4afc',
    messagingSenderId: '33236853941',
    projectId: 'sharaby-center',
    storageBucket: 'sharaby-center.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaeXPAeWsra9T82Lx_B3iRuOPOBEXdJ4Y',
    appId: '1:33236853941:ios:8cf7f5d2f6e9d1c18b4afc',
    messagingSenderId: '33236853941',
    projectId: 'sharaby-center',
    storageBucket: 'sharaby-center.firebasestorage.app',
    iosBundleId: 'com.example.sharabyCenterClinic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaeXPAeWsra9T82Lx_B3iRuOPOBEXdJ4Y',
    appId: '1:33236853941:ios:8cf7f5d2f6e9d1c18b4afc',
    messagingSenderId: '33236853941',
    projectId: 'sharaby-center',
    storageBucket: 'sharaby-center.firebasestorage.app',
    iosBundleId: 'com.example.sharabyCenterClinic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdniS7y5aIY0Ds_zqSnVfuTet3pS6fL3c',
    appId: '1:33236853941:web:fd4db1c7ee52cb918b4afc',
    messagingSenderId: '33236853941',
    projectId: 'sharaby-center',
    authDomain: 'sharaby-center.firebaseapp.com',
    storageBucket: 'sharaby-center.firebasestorage.app',
    measurementId: 'G-MFHPDG5NNH',
  );
}
